apiVersion: apps/v1
kind: Deployment
metadata:
  name: jump
  labels:
    app: jump
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jump
  template:
    metadata:
      labels:
        app: jump
    spec:
      containers:
      - name: jump
        image: kcorer/jump
        ports:
        - containerPort: 8888
        readinessProbe:
          httpGet:
            #path: /doesNotExist
            path: /
            port: 8888
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            #path: /doesNotExist
            path: /
            port: 8888
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: jump
spec:
  selector:
    app: jump
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
